// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: tafs.proto
#ifndef GRPC_tafs_2eproto__INCLUDED
#define GRPC_tafs_2eproto__INCLUDED

#include "tafs.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace tafs {

class ToyAFS GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SayHello(::grpc::ClientContext* context, const ::tafs::HelloRequest& request, ::tafs::HelloReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tafs::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::tafs::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tafs::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    virtual ::grpc::Status Login(::grpc::ClientContext* context, const ::tafs::LoginRequest& request, ::tafs::LoginReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tafs::LoginReply>> AsyncLogin(::grpc::ClientContext* context, const ::tafs::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tafs::LoginReply>>(AsyncLoginRaw(context, request, cq));
    }
    virtual ::grpc::Status TestBytes(::grpc::ClientContext* context, const ::tafs::TestB& request, ::tafs::LoginReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tafs::LoginReply>> AsyncTestBytes(::grpc::ClientContext* context, const ::tafs::TestB& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tafs::LoginReply>>(AsyncTestBytesRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tafs::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::tafs::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tafs::LoginReply>* AsyncLoginRaw(::grpc::ClientContext* context, const ::tafs::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tafs::LoginReply>* AsyncTestBytesRaw(::grpc::ClientContext* context, const ::tafs::TestB& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    ::grpc::Status SayHello(::grpc::ClientContext* context, const ::tafs::HelloRequest& request, ::tafs::HelloReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tafs::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::tafs::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tafs::HelloReply>>(AsyncSayHelloRaw(context, request, cq));
    }
    ::grpc::Status Login(::grpc::ClientContext* context, const ::tafs::LoginRequest& request, ::tafs::LoginReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tafs::LoginReply>> AsyncLogin(::grpc::ClientContext* context, const ::tafs::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tafs::LoginReply>>(AsyncLoginRaw(context, request, cq));
    }
    ::grpc::Status TestBytes(::grpc::ClientContext* context, const ::tafs::TestB& request, ::tafs::LoginReply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tafs::LoginReply>> AsyncTestBytes(::grpc::ClientContext* context, const ::tafs::TestB& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tafs::LoginReply>>(AsyncTestBytesRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientAsyncResponseReader< ::tafs::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::tafs::HelloRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::tafs::LoginReply>* AsyncLoginRaw(::grpc::ClientContext* context, const ::tafs::LoginRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::tafs::LoginReply>* AsyncTestBytesRaw(::grpc::ClientContext* context, const ::tafs::TestB& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_SayHello_;
    const ::grpc::RpcMethod rpcmethod_Login_;
    const ::grpc::RpcMethod rpcmethod_TestBytes_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::tafs::HelloRequest* request, ::tafs::HelloReply* response);
    virtual ::grpc::Status Login(::grpc::ServerContext* context, const ::tafs::LoginRequest* request, ::tafs::LoginReply* response);
    virtual ::grpc::Status TestBytes(::grpc::ServerContext* context, const ::tafs::TestB* request, ::tafs::LoginReply* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    std::unique_ptr< ::grpc::RpcService> service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestSayHello(::grpc::ServerContext* context, ::tafs::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::tafs::HelloReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestLogin(::grpc::ServerContext* context, ::tafs::LoginRequest* request, ::grpc::ServerAsyncResponseWriter< ::tafs::LoginReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestTestBytes(::grpc::ServerContext* context, ::tafs::TestB* request, ::grpc::ServerAsyncResponseWriter< ::tafs::LoginReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace tafs


#endif  // GRPC_tafs_2eproto__INCLUDED
